# Generated by Django 2.1.5 on 2019-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_text', models.CharField(max_length=50)),
                ('enrolled', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
