# Generated by Django 2.1.5 on 2019-02-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Classe',
        ),
    ]
