# Generated by Django 2.1.5 on 2019-02-26 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190226_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classID',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
