# Generated by Django 2.1.5 on 2019-02-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_classe_classid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classe',
            new_name='Course',
        ),
    ]
