# Generated by Django 2.1.5 on 2019-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20190226_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=40)),
                ('instructor_id', models.CharField(max_length=20)),
                ('instructor_age', models.CharField(max_length=3)),
            ],
        ),
    ]
