# Generated by Django 2.1.5 on 2019-02-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20190226_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='i_age',
            new_name='i_tenure',
        ),
    ]
