# Generated by Django 2.1.5 on 2019-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20190227_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classID',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='classname',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='student_name',
        ),
    ]
