# Generated by Django 2.1.5 on 2019-03-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20190312_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('class_name',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Instructor'),
        ),
    ]
